INSERT INTO public.neighborhoods (
  name,
  normalized_name,
  city,
  state
)
VALUES
  ('Alto da Boa Vista', 'alto da boa vista', 'Petrolina', 'PE'),
  ('Alto do Cocar', 'alto do cocar', 'Petrolina', 'PE'),
  ('Alto Grande', 'alto grande', 'Petrolina', 'PE'),
  ('Antônio Cassimiro', 'antonio cassimiro', 'Petrolina', 'PE'),
  ('Areia Branca', 'areia branca', 'Petrolina', 'PE'),
  ('Atrás da Banca', 'atras da banca', 'Petrolina', 'PE'),
  ('Bela Vista', 'bela vista', 'Petrolina', 'PE'),
  ('Boa Esperança', 'boa esperanca', 'Petrolina', 'PE'),
  ('Caminho do Sol', 'caminho do sol', 'Petrolina', 'PE'),
  ('Carneiros', 'carneiros', 'Petrolina', 'PE'),
  ('Centro', 'centro', 'Petrolina', 'PE'),
  ('Cidade Jardim', 'cidade jardim', 'Petrolina', 'PE'),
  ('Cidade Universitária', 'cidade universitaria', 'Petrolina', 'PE'),
  ('Cohab IV', 'cohab iv', 'Petrolina', 'PE'),
  ('Cohab V', 'cohab v', 'Petrolina', 'PE'),
  ('Cohab VI', 'cohab vi', 'Petrolina', 'PE'),
  ('Cohab Massangano', 'cohab massangano', 'Petrolina', 'PE'),
  ('Cohab São Francisco', 'cohab sao francisco', 'Petrolina', 'PE'),
  ('Colina Imperial', 'colina imperial', 'Petrolina', 'PE'),
  ('Colinas do Rio', 'colinas do rio', 'Petrolina', 'PE'),
  ('Colônia Imperial', 'colonia imperial', 'Petrolina', 'PE'),
  ('Cosme e Damião', 'cosme e damiao', 'Petrolina', 'PE'),
  ('Dom Avelar', 'dom avelar', 'Petrolina', 'PE'),
  ('Dom Malan', 'dom malan', 'Petrolina', 'PE'),
  ('Dona Alexandrina', 'dona alexandrina', 'Petrolina', 'PE'),
  ('Distrito Industrial', 'distrito industrial', 'Petrolina', 'PE'),
  ('Fernando Idalino', 'fernando idalino', 'Petrolina', 'PE'),
  ('Gercino Coelho', 'gercino coelho', 'Petrolina', 'PE'),
  ('Henrique Leite', 'henrique leite', 'Petrolina', 'PE'),
  ('IPSEP', 'ipsep', 'Petrolina', 'PE'),
  ('Jardim Amazonas', 'jardim amazonas', 'Petrolina', 'PE'),
  ('Jardim Guararapes', 'jardim guararapes', 'Petrolina', 'PE'),
  ('Jardim Maravilha', 'jardim maravilha', 'Petrolina', 'PE'),
  ('Jardim Petrópolis', 'jardim petropolis', 'Petrolina', 'PE'),
  ('Jardim São Paulo', 'jardim sao paulo', 'Petrolina', 'PE'),
  ('Jatobá', 'jatoba', 'Petrolina', 'PE'),
  ('João de Deus', 'joao de deus', 'Petrolina', 'PE'),
  ('José e Maria', 'jose e maria', 'Petrolina', 'PE'),
  ('Km 2', 'km 2', 'Petrolina', 'PE'),
  ('Loteamento Bela Vista', 'loteamento bela vista', 'Petrolina', 'PE'),
  ('Loteamento Recife', 'loteamento recife', 'Petrolina', 'PE'),
  ('Loteamento Padre Cícero', 'loteamento padre cicero', 'Petrolina', 'PE'),
  ('Mandacaru', 'mandacaru', 'Petrolina', 'PE'),
  ('Maria Auxiliadora', 'maria auxiliadora', 'Petrolina', 'PE'),
  ('Monsenhor Bernardino', 'monsenhor bernardino', 'Petrolina', 'PE'),
  ('Nossa Senhora Rainha dos Anjos', 'nossa senhora rainha dos anjos', 'Petrolina', 'PE'),
  ('Nova Petrolina', 'nova petrolina', 'Petrolina', 'PE'),
  ('Novo Horizonte', 'novo horizonte', 'Petrolina', 'PE'),
  ('Ouro Preto', 'ouro preto', 'Petrolina', 'PE'),
  ('Palhinhas', 'palhinhas', 'Petrolina', 'PE'),
  ('Padre Cícero', 'padre cicero', 'Petrolina', 'PE'),
  ('Pedra do Bode', 'pedra do bode', 'Petrolina', 'PE'),
  ('Pedra Linda', 'pedra linda', 'Petrolina', 'PE'),
  ('Pedro Raimundo', 'pedro raimundo', 'Petrolina', 'PE'),
  ('Portal da Cidade', 'portal da cidade', 'Petrolina', 'PE'),
  ('Quati', 'quati', 'Petrolina', 'PE'),
  ('Rio Claro', 'rio claro', 'Petrolina', 'PE'),
  ('Rio Corrente', 'rio corrente', 'Petrolina', 'PE'),
  ('Rio Jordão', 'rio jordao', 'Petrolina', 'PE'),
  ('Santa Bárbara', 'santa barbara', 'Petrolina', 'PE'),
  ('Santa Luzia', 'santa luzia', 'Petrolina', 'PE'),
  ('São Gonçalo', 'sao goncalo', 'Petrolina', 'PE'),
  ('São Joaquim', 'sao joaquim', 'Petrolina', 'PE'),
  ('São Jorge', 'sao jorge', 'Petrolina', 'PE'),
  ('São José', 'sao jose', 'Petrolina', 'PE'),
  ('Terras do Sul', 'terras do sul', 'Petrolina', 'PE'),
  ('Topázio', 'topazio', 'Petrolina', 'PE'),
  ('Vale Dourado', 'vale dourado', 'Petrolina', 'PE'),
  ('Vale Grande Rio', 'vale grande rio', 'Petrolina', 'PE'),
  ('Vila Débora', 'vila debora', 'Petrolina', 'PE'),
  ('Vila dos Ingás', 'vila dos ingas', 'Petrolina', 'PE'),
  ('Vila dos Ingás II', 'vila dos ingas ii', 'Petrolina', 'PE'),
  ('Vila Eduardo', 'vila eduardo', 'Petrolina', 'PE'),
  ('Vila Eulália', 'vila eulalia', 'Petrolina', 'PE'),
  ('Vila Esperança', 'vila esperanca', 'Petrolina', 'PE'),
  ('Vila Marcela', 'vila marcela', 'Petrolina', 'PE'),
  ('Vila Mocó', 'vila moco', 'Petrolina', 'PE'),
  ('Vila Vitória', 'vila vitoria', 'Petrolina', 'PE'),
  ('Vivendas', 'vivendas', 'Petrolina', 'PE')
ON CONFLICT (normalized_name, city, state)
DO NOTHING;